[build-system]										
requires = ["setuptools>=64", "wheel"]                                                  
build-backend = "setuptools.build_meta"                                                 

[project]                                                                               
name = "autoQY"                                                                    
version = "1.0.0"                                                                       
description = "GUI for quantum yield calculation"
license = "GPL-3.0-or-later"         							
readme = "README.md"                                                                    
requires-python = ">=3.1"
                                                                                        
authors = [                                                                             
  { name = "Jorn Steen", email = "jorn.steen@kemi.uu.se" },
  { name = "Alfredo Bellisario", email = "alfredo.bellisario@physics.uu.se" },
  { name = "Stefano Crespi", email = "stefano.crespi@kemi.uu.se" }
]                                                                                       
                                                                                        
dependencies = [                                                                        
  'numpy>=2.2.2',
  'scipy>=1.15.1',
  'lmfit>=1.3.2',
  'pandas>=2.2.3',
  'PyQt5',
  'matplotlib>=3.10.0'
]

keywords = [
  "science",
  "spectroscopy"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Scientific/Engineering :: Spectroscopy",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.urls]
Homepage = "https://github.com/CrespiLab/autoQY"

[project.scripts]
autoqy = "main.main:main"

[tool.setuptools]
packages = [
  'main',
  'PowerProcessing',
  'QY',
  'tools',
  'UIs'
]

